apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    service: postgres
    environment: production
spec:
  selector:
    service: postgres
  type: NodePort
  ports:
  - name: postgresport
    port:  {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
status:
  loadBalancer: {}
