apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: verge
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: verge
              servicePort: 80
          - path: /daskboard
            backend:
              serviceName: dask-scheduler
              servicePort: 8787
