apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  labels:
    service: dask-scheduler
spec:
  type: NodePort
  ports:
    - name: daskport
      port: 8786
      targetPort: 8786
    - name: webuiport
      port: 8787
      targetPort: 8787
  selector:
    service: dask-scheduler