apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: arnheim-files
  labels:
    service: arnheim-files
    environment: production
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}
