apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: arnheim-media
  labels:
    service: arnheim-media
    environment: production
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}
