apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: postgresdata
  labels:
    service: postgresdata
    environment: production
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}
